
version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: task_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: taskmanager
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - task_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/taskmanager?authSource=admin
      PORT: 5000
    depends_on:
      - mongodb
    networks:
      - task_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - task_network

volumes:
  mongodb_data:

networks:
  task_network:
    driver: bridge
